import { FormJSON } from "../types";

export const json: FormJSON = {
  description: "This is a sample Form Builder",
  completedMessage: "Thank you for your submission!",
  title: "Simple Form Builder",
  elements: [
    {
      type: "text",
      name: "firstName",
      title: "First Name",
      description: "Please type your first name",
      isRequired: true,
      minWidth: "256px",
      maxWidth: "28%",
      value: "",
      defaultValue: "Rasoul",
    },
    {
      type: "text",
      name: "lastName",
      title: "Last Name",
      description: "Please type your last name",
      isRequired: true,
      minWidth: "256px",
      maxWidth: "28%",
      value: "",
      defaultValue: "",
    },
    {
      type: "text",
      name: "occupation",
      title: "Occupation",
      description: "Please type your occupation",
      isRequired: false,
      minWidth: "256px",
      maxWidth: "55%",
      value: "",
      defaultValue: "",
    },
    {
      type: "checkbox",
      name: "married",
      title: "Marriage",
      description: "What is your marital status?",
      isRequired: true,
      options: [
        { text: "Single", value: "single" },
        { text: "Married", value: "married" },
        { text: "Divorced", value: "divorced" },
        { text: "Widowed", value: "widowed" },
      ],
      value: [],
      defaultValue: [],
    },
    {
      type: "radio",
      name: "nationality",
      title: "Nationality",
      description: "What is your nationality?",
      isRequired: true,
      options: [
        { text: "Iranian", value: "iranian" },
        { text: "Other", value: "other" },
      ],
      value: "",
      defaultValue: "iranian",
    },
    {
      type: "select",
      name: "gender",
      title: "Gender",
      description: "What is your gender?",
      isRequired: true,
      options: [
        { text: "Male", value: "male" },
        { text: "Female", value: "female" },
      ],
      value: "",
      defaultValue: "male",
    },
  ],
  showQuestionNumbers: "off",
  questionTitleLocation: "left",
  questionDescriptionLocation: "underInput",
  questionErrorLocation: "bottom",
  completeText: "SUBMIT",
};
